[package]
name = "async-imap"
version = "0.12.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
documentation = "https://docs.rs/async-imap/"
repository = "https://github.com/async-email/async-imap"
homepage = "https://github.com/async-email/async-imap"
description = "Async IMAP client for Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "async-email/async-imap" }
is-it-maintained-open-issues = { repository = "async-email/async-imap" }

[features]
default = ["runtime-async-std"]
compress = ["async-compression"]

runtime-async-std = ["async-std", "async-compression?/futures-io"]
runtime-tokio = ["tokio", "async-compression?/tokio"]

[dependencies]
async-channel = "2.5.0"
async-compression = { version = "0.4.50", default-features = false, features = ["deflate"], optional = true }
async-std = { version = "1.13.2", default-features = false, features = ["std", "unstable"], optional = true }
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
bytes = "1.12.1"
chrono = { version = "0.4.45", default-features = false, features = ["std"] }
futures-util = { version = "0.3.34", features = ["io"] }
imap-proto = "0.17.0"
log = "0.4.34"
nom = "8.0.0"
pin-project = "1.1.13"
pin-utils = "0.1.1"
self_cell = "1.3.0"
stop-token = "0.7.0"
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["sync", "time", "io-util"], optional = true }

[dev-dependencies]
async-std = { version = "1.13.2", features = ["std", "attributes"] }
pretty_assertions = "1.4.1"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "net"] }
