[package]
name = "async-imap-examples"
version = "0.1.0"
publish = false
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
edition = "2018"

[features]
default = ["runtime-async-std"]

runtime-async-std = ["async-std", "async-native-tls/runtime-smol", "async-smtp/runtime-async-std", "async-imap/runtime-async-std"]
runtime-tokio = ["tokio", "async-native-tls/runtime-tokio", "async-smtp/runtime-tokio", "async-imap/runtime-tokio"]

[dependencies]
anyhow = "1.0.104"
async-imap = { path = "../", default-features = false }
async-native-tls = { version = "0.6.0", default-features = false }
async-smtp = { version = "0.10.2", default-features = false }

async-std = { version = "1.13.2", features = ["std", "attributes"], optional = true }
futures-executor = "0.3.34"
futures-util = { version = "0.3.34", features = ["io"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "net"], optional = true }
